# **KNN CLASSIFIER**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns

In [ ]:
df=pd.read_csv("refined_mobile_prices.csv")

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
neigh=KNeighborsClassifier()

In [ ]:
x=df.drop("price_range",axis=1)
y=df["price_range"]

In [ ]:
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df,y,random_state=2)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
neigh=KNeighborsClassifier()

In [ ]:
model=neigh.fit(X_train,y_train)

In [ ]:
neigh.score(X_test,y_test)

0.926

# **DECISION TREE**

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,y_train)
y_pred_dt=dt_model.predict(X_test)

print("Decision tree accuracy: ",dt_model.score(X_test,y_test))

Decision tree accuracy:  1.0


# **Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train,y_train)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest accuracy: ",rf_model.score(X_test,y_test))

Random Forest accuracy:  1.0


# **Naive Bayes Classifier**

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# Create an instance of Gaussian Naive Bayes
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
# Make predictions on the test set
y_pred = gnb.predict(X_test)

In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

# Classification report
class_report = classification_report(y_test, y_pred)
print('Classification Report:\n', class_report)


Accuracy: 1.00
Confusion Matrix:
 [[122   0   0   0]
 [  0 133   0   0]
 [  0   0 119   0]
 [  0   0   0 126]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       122
           1       1.00      1.00      1.00       133
           2       1.00      1.00      1.00       119
           3       1.00      1.00      1.00       126

    accuracy                           1.00       500
   macro avg       1.00      1.00      1.00       500
weighted avg       1.00      1.00      1.00       500



# **SVM Classifier**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# Handle missing values (if any)
df = df.dropna()

# Encode categorical variables (if applicable)
df = pd.get_dummies(df, drop_first=True)

# Define features (X) and target (y)
X = df.drop('price_range', axis=1)  # Features
y = df['price_range']  # Target variable

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create an instance of the SVM classifier
svm_classifier = SVC(kernel='linear')  # You can change the kernel as needed (e.g., 'rbf', 'poly', etc.)

# Train the model
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
# Make predictions on the test set
y_pred = svm_classifier.predict(X_test)

In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

# Classification report
class_report = classification_report(y_test, y_pred)
print('Classification Report:\n', class_report)


Accuracy: 0.97
Confusion Matrix:
 [[ 99   6   0   0]
 [  0  91   0   0]
 [  0   3  87   2]
 [  0   0   1 111]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.94      0.97       105
           1       0.91      1.00      0.95        91
           2       0.99      0.95      0.97        92
           3       0.98      0.99      0.99       112

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [ ]:
# Initialize classifiers
classifiers = {
    'KNN': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC()
}

# Loop through the classifiers, fit them, make predictions, and calculate precision
for name, clf in classifiers.items():
    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = clf.predict(X_test)

    # Calculate precision
    precision = precision_score(y_test, y_pred, average='weighted')  # Use 'weighted' for multi-class
    print(f'{name} Precision: {precision:.2f}')


KNN Precision: 0.94
Decision Tree Precision: 0.84
Random Forest Precision: 0.88
Naive Bayes Precision: 0.81
SVM Precision: 0.97
